nuxt-community/auth-module

src/index.js
templates/auth.store.js

This module imports the entirety of Lodash which is very large. This results in large bundle sizes for anyone consuming this module. 
This PR imports only the merge function from Lodash.

Import less Lodash

---

README.md

redirect config was moved and renamed in 3.0, readme was incorrect though

Update redirect config in documentation

---

README.md
lib/module.js
lib/templates/auth.store.js

Not always we need to store the token as Cookie and LocalStorage at the same time

Let LocalStorage to be optional

---

README.md
lib/module.js
lib/templates/auth.store.js

Adding option fetchUser which allows control of fetching authenticated user.
cc @pi0

Add option fetchUser

---

lib/templates/auth.store.js

With this change the `token` name can be `data.token` for example.
eg Response: 
```json
{
"data": {
...
"token": "..."
}
}
```
I've not checked for BC, but in theory it should be fine.... right?

Allow `token` to be a nested object in the response

---

README.md
lib/module.js
lib/templates/auth.middleware.js
lib/templates/auth.plugin.js

- Automatically redirect on login and logout by watching `auth/loggedIn` getter, when this getter changes the plugins will automatically redirect to either login or logged pages.
See 91f808a for details.
- Reducing Middleware code redundancy by integrating `no-auth` middleware to `auth` middleware, disabling guest or logged users redirection is now done through `nuxt.config.js` options.
Module options :
```js
redirect: {
// Set this if you want to redirect unauthenticated users to notLoggedIn
guest: true,
// Set this if you want to redirect authenticated users to loggedIn
user: true,
notLoggedIn: '/login',
loggedIn: '/'
}
```
Middleware configuration :
```js
// ... in nuxt.config.js ...
router: {
middleware: [
'auth',
]
}
```
- (#42 inspired)  You can now exclude components from being …

feature and fix: redirect on login & logout - excluding components from middleware..

---

lib/templates/auth.middleware.js

While cleaning up the code and refactoring it a bit, it seems that a little mistake got in there:
```diff
-- if (!isRouteGuarded(route)) {
++ if (isRouteGuarded(route)) {
```
`isRouteGuarded` return the `guarded` option value, which is either:
- `undefined` - happens when the option `guarded` is not set into our components.
- `true` - happens when the option `guarded` is set to `true`
- `false` - happens when the option `guarded` is set to `true`
With the current line `if (!isRouteGuarded(route))` our middleware will not act as intended, if the `guarded` option is false, it will become `true` with the type inversion operator.
Should the `isRouteGuarded` be renamed for more clarity, or patch it as proposed in this PR?

fix: guard check in middleware

---

lib/auth/schemes/local.js
test/module.test.js

References #57 
After a logout the axios token should be cleared so subsequent api requests do not use the logged out user's credentials.

Clear axios token after logout

---

examples/demo/nuxt.config.js
lib/auth/providers/_utils.js
lib/module.js

userinfo & scope would need to be alterable.

Allow providers params to be overloaded from nuxt.config.js

---

docs/options.md
lib/auth/auth.js
lib/defaults.js

Currently, only `this.$route.path` is used for redirecting back after login. I've added an option so `this.$route.fullPath` can be used as well.
PS: @pi0 Any chance to see a release for that feature on master (if I PR it there) soon?

Add full path redirect option

---

lib/auth/auth.js

This is a fix for the following issue: https://nuxtjs.cmty.io/nuxt/docs/issues/c84

Fix No Token exception when tokenRequired is set to false

---

docs/schemes/oauth2.md
lib/schemes/oauth2.js

nuxt-community/auth-module#119

Add option to use IdToken instead of AccessToken

---

lib/schemes/local.js

This is a fix for
https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c90
Setting the `logout` strategy to `false` will effectively mean that
logout does nothing (it simple returns).
However, when you have a stateless API, and no need to call
a logout endpoint, you still want the user to be logged out
in the browser (token removed, session reset, that sort of stuff).
This change handles that by not returning if the logout option
is falsy, but instead only skipping over the networking part.
I think this is the behaviour people would expect when they set
logout to `false`.

Added support for logging out without an API endpoint

---

lib/core/middleware.js
lib/core/utilities.js

As logged in issue https://github.com/nuxt-community/auth-module/issues/126, when the `auth` middleware is applied globally, non-authenticated users who hit non-existant routes (e.g. /asdf/asdf) get redirected to the login page. IMO, these should flow through to the 404 error page.
Notes:
* Borrowed the getMatchedComponents method from the Nuxt core utils.
* I hope I'm not opening up any potential security hole here?! Sanity check would be awesome

Let 404s surface when auth middleware applied globally.

---

lib/core/middleware.js

Also, if dev has disabled redirect (all or callback/login), supported according to the [options](https://auth.nuxtjs.org/options.html#redirect) documentation, don't let that affect the middleware here.

Don't redirect callback to login when using 'auth' globally

---

docs/options.md

Addresses issue: https://github.com/nuxt-community/auth-module/issues/122

Update options.md documentation to reflect current

---

docs/schemes/oauth2.md
lib/core/auth.js
lib/module/defaults.js
lib/schemes/oauth2.js

- Fix url
- Add missing parameters for "Authorization Code Grant" flow.
- Automatically store the refresh_token, if it exists

Full support "Authorization Code Grant" & Refresh Token

---

lib/schemes/local.js

This is a fix for issue #136. When using the local authentication strategy, we need to "logout locally" before attempting to log in, so we're not sending (e.g.) an expired token along with the login request.
This moves the local functionality out of the `logout()` method and calls it from both `login` and `logout`.

Logout locally before logging in

---

lib/schemes/local.js

Sometimes we need to change token key name in requests header, in order to support custom token name we could define new option in local strategy. lets call it `tokenName`
```
auth: {
strategies: {
local: {
tokenName: 'x-auth',
endpoints: ...
}
}
}
```

Add support for custom token key in request header

---

lib/core/storage.js

The `ctx.req` only exist on server side (https://nuxtjs.org/api/context/), this function will never be executed on client side.
By the way : thanks for this module :+1:

fix: Storage cookie get on client side

---

lib/core/auth.js

If you load a page with auth directly from the URL bar (or refresh the page) you will allways be redirected to `home`. This is simply because the user gets re-logged in, and the watcher will trigger the `loggedIn` redirect.
Now, as soon as we move to another page, `this.ctx.from` is being added so we know the previous page.
This means that on the initial load, ctx.from is not avaible.
Because of that, a check in the `watchState` to see if `ctx.from` excists should disable the redirect only on first direct load of a page.

Fix: no more redirect on direct load / refresh of a page.

---

docs/SUMMARY.md
docs/providers/passport.md
lib/providers/laravel.passport.js
lib/providers/passport.js
lib/schemes/oauth2.js

This would add a "passport" provider for easy integration with [Laravel Passport](https://laravel.com/docs/5.6/passport).

Add a Laravel Passport Provider

---

docs/providers/github.md
lib/providers/_utils.js

Fix issue with using `jsonMiddleware` for form encoded data. Update documentation to indicate that `client_secret` is required.

Fix Github provider

---

docs/providers/passport.md

Didn't completely update the docs to reflect name change to from `passport` to `laravel.passport`.

Fix typo in Laravel Passport docs

---

lib/core/utilities.js

When running nuxt in "spa" mode sometimes returns the exception "client.js:49 TypeError: Cannot read property 'auth' of undefined", seems like a strict mode error,
The full error:
client.js:49 TypeError: Cannot read property 'auth' of undefined
at utilities.js:35
at Array.some (<anonymous>)
at utilities.js:34
at Array.some (<anonymous>)
at routeOption (utilities.js:31)
at Vue.<anonymous> (auth.js:29)
at Watcher.run (vue.runtime.esm.js:3229)
at flushSchedulerQueue (vue.runtime.esm.js:2977)
at Array.<anonymous> (vue.runtime.esm.js:1833)
at flushCallbacks (vue.runtime.esm.js:1754)

Fix an exception when running the auth plugin in spa mode

---

lib/providers/_utils.js
lib/providers/laravel.passport.js

The oauth scheme [sends `code`, `client_id`, `redirect_uri`, `response_type` and `grant_type`](https://github.com/nuxt-community/auth-module/blob/dev/lib/schemes/oauth2.js#L103-L109) to the authentication provider. When using the Github provider, a [`serverMiddleware` is added](https://github.com/nuxt-community/auth-module/blob/dev/lib/providers/_utils.js#L28-L61) to attach the `client_secret` and proxy the request on through to Github.
Currently, the server middleware only passes the `client_id`, `client_secret` and `code` no matter what is sent to it. This pull request would ensure that the `redirect_uri`, `response_type` and `grant_type` are also included.
Additionally, this change will allow the laravel.passport provider to re-use the `addAuthorize` method.

Add redirect_uri, response_type and grant_type to server-side authentication request

---

lib/schemes/oauth2.js

@pi0 Here is! Followed same guidelines from LOCAL STRATEGY, because OAUTH2 STRATEGY also deserves it :)
What does it? Automatically set axios token on requests, if it exists. Also clear token from headers after logout.

Oauth2: set axios token

---

docs/api/auth.md
lib/core/auth.js

This is another proposal to address #162 
It adds an `onRedirect` hook that can be defined in a plugin in order to pre-process the URL before the redirect happens.
To use this with **nuxt-i18n**, you could do something like this:
```js
// ~/plugins/auth.js
export default ({ app }) => {
$auth.onRedirect(to => {
return app.localePath(to)
})
})
```

feat: Add onRedirect hook to pre-process URLs before redirection

---

docs/schemes/local.md
docs/schemes/oauth2.md
lib/schemes/local.js
lib/schemes/oauth2.js
package.json
yarn.lock

https://github.com/nuxt-community/auth-module/issues/120
I wasn't able to add a function directly to `nuxt.config.js` (I think the config normalizer wasn't expecting a function) so I added a config prop that will override the `userinfo` ajax call and instead calculate the user object using `JSON.parse(atob(token.split('.')[1]))`.

Add function to compute user obj from token

---

docs/options.md
lib/core/auth.js

Bring back resetOnError

---

docs/schemes/README.md

add minor proper english revisions

---

docs/api/storage.md

`getLocalstorage` can't execute but `getLocalStorage` can.

fix a document about storage.md

---

lib/providers/_utils.js
lib/providers/auth0.js
lib/schemes/oauth2.js

Allows and defaults to adding audience field to Auth0 requests in order to return a JWT. Fixes #176.

Add audience to Auth0 request. Fixes #176.

---

docs/schemes/local.md

Setting propertyName to `undefined` forces the default value because of [Object.assign()](https://github.com/nuxt-community/auth-module/blob/dev/lib/core/auth.js#L248).
propertyName should be not undefined but falsy for Object.assign() not to rewrite it.

Documentation fix: propertyName needed to grab the full API response

---

lib/core/middleware.js
lib/core/utilities.js

In middleware.js file it checks for login route to redirect:
```
if (!login || ctx.route.path === login.split('?')[0]) {
ctx.app.$auth.redirect('home')
}
```
the `login ` is   `const { login, callback } = ctx.app.$auth.options.redirect` so it is constant.
for example `/login`. In `if` condition it should split `ctx.route.path` and then checks it with login.
And there is another problem. In some cases the login route path is `/login/`. So I added a helper function
and it splits the path and remove `/` from the path.
the function:
```
const splitPath = path => {
// remove query string
let result = path.split('?')[0]
// remove redundant / from the end of path
if (result.charAt(result.length - 1) === '/') {
result = result.slice(0, -1)
}
return result
}
```
new `if` condition:
```
if (!login …
```

fix(auth): add path helper function

---

docs/README.md
docs/SUMMARY.md
docs/providers/github.md
examples/demo/layouts/default.vue
examples/demo/pages/login.vue

Replace to `GitHub` from `Github` in documents.

Fix GitHub capitalize

---

docs/api/auth.md
lib/core/auth.js
lib/schemes/local.js

After registration and reseting a password, my api returns an auth token and which I would like to use to set the current user.
To do this currently, I was using code that looks like this:
``` js
const token = `Bearer ${data.access_token}`
this.$auth.setToken(this.$store.state.auth.strategy, token)
this.$auth.strategy._setToken(token)
return this.$auth.fetchUser()
```
I believe this is a common use case, so this pr adds a function `$auth.setUserToken(token)` to correctly set the user with an auth code. The function `setToken` does not set the Authorization header, so it doesn't handle this use case very well.
Thanks!

setUserToken

---

docs/api/auth.md

Some of the headings had the wrong sizes, which was making the document outline render incorrectly:
https://auth.nuxtjs.org/api/auth

docs: fix heading levels on auth page

---

docs/api/auth.md

It seems to need context.app.$auth to work.
I copied the approach used in https://auth.nuxtjs.org/recipes/extend and it worked.
Thanks for the excellent module BTW :+1:

docs: fix onError example

---

lib/schemes/local.js

This fixes an issue with the local scheme which sets the user to `{}` even if there's no token, which causes loggedIn to report true, when in fact it's false.

fix(local): prevent `loggedIn` being incorrectly set to true when user is disabled

---

docs/schemes/oauth2.md
lib/schemes/oauth2.js

Enables one to add extra params to oauth2 authorization endpoint before
navigating to it.
fixes #349

feat(oauth2): support passing extra query params

---

lib/core/auth.js
lib/core/storage.js
lib/core/utilities.js
lib/module/plugin.js
lib/schemes/oauth2.js

Currently the auth-module is throwing `process.browser is deprecated, use process.client instead.` warnings. This pull request replaces all `process.browser` instances with `process.client`.
https://github.com/nuxt/nuxt.js/issues/4106

refactor: replace deprecated `process.browser` with `process.client`

---

docs/middleware.md
lib/core/middleware.js

In most cases you need to create `guest` middleware:
```js
// middleware/guest.js
export default function({ store, redirect }) {
if (store.state.auth.loggedIn) {
return redirect('/');
}
}
```
With this feature I can simply add an option:
> No need to create a new middleware.
```html
// pages/guest.vue
<template>
<div>guest</div>
</tempalte>
<script>
export default {
middleware: ['auth'],
options: {
auth: 'guest'
}
}
</script>
```

feat(middleware): add guest option in auth middleware

---

lib/core/storage.js
lib/core/utilities.js

[universal-storage](https://github.com/nuxt-community/universal-storage) is using a forked and enhanced version of auth-module's storage. Main improvements:
- Universal cookies support
- Auto object and primitives serialization and deserialization
- Heavily tested on alibaba.aero

feat: improve storage

---

lib/module/index.js

Fixed a bug when 'no strategy defined!' is displayed when options.defaultStrategy is set.
Added a warning when the strategy specified in options.defaultStrategy is not a valid strategy.

fix(module): warn if default strategy is not valid

---

lib/core/storage.js

Explanation. nodejs expects setHeader('Set-Cookie', value) to be
an array. If given a string it will accept and properly send it.
However, any subsequent attempts to replace the string with an array
to send multiple Set-Cookie headers will fail; it will instead send a
single Set-Cookie header with a concatenated array. The client will only
parse the first cookie, and then you'll spend hours pulling your
hair out.
Example:
res.SetHeader('Set-Cookie', 'serialized cookie')
res.SetHeader('Set-Cookie', ['serialized cookie','another cookie'])
generates
Set-Cookie: serialized cookie,another cookie
when what you want is
Set-Cookie: serialized cookie
Set-Cookie: another cookie

fix: server side Set-Cookie always set an array.

---

docs/api/options.md

The link on the options page to the extend recipe was relative to the
api directory but the file was not.

docs: fix path to plugin extend documentation

---

lib/core/storage.js

relate #367 
Set-Cookie header contains `undefined` value when `prevCookies` is empty

fix: set-cookie header contains `undefined` value

---

docs/providers/auth0.md

As discussed in issue #375 there's a new setting that's automatically enabled in new Auth0 tenants, which means that logged out users that log back in a short while later are automatically logged in. Auth0 doesn't show the login page. 
This extra bit of documentation explains to work around this, as described in issue #375.

In docs add logout info re Auth0

---

docs/schemes/oauth2.md
lib/schemes/oauth2.js

Added support for access_type=offline, required by Google Oauth code exchange authorization flow to get refresh token on first login.
See https://developers.google.com/identity/protocols/OpenIDConnect#refresh-tokens
I set the default value for access-type to 'online', as this is the normal case when not doing a code exchange.

feat(oauth2): support `access_type=offline` to enable refresh tokens from google

---

lib/core/middleware.js

At the moment when `auth: 'guest'` is set on a page it always redirect an unauthed user to `login`, which I think is not the desired effect.
This PR fixes this, as unauthed users are now not redirected to `login`.
I also took the liberty to make the code more self-explanatory.
Related issue: #383

fix: don't redirect to login page if in guest mode

---

docs/api/auth.md
docs/recipes/extend.md
lib/core/middleware.js
lib/module/plugin.js
lib/schemes/oauth2.js
package.json
test/fixtures/basic/plugins/auth.js
yarn.lock

**Bonus:** I added `$auth` in context for easier usage in `asyncData`
This PR is to enhance the DX on the callback redirect page to support SSR redirect.
It also avoid calling the provider (ex: GitHub) if the query params are not on the callback route.
Before:
After:

feat(oauth2): support server-side callback

---

lib/schemes/oauth2.js

This fixes #393
Problem is that with the latest introduction of server-side callback handling #381, the parsing of the hash was removed and therefore the information provided by the oauth clients can not be extracted anymore.

fix(oauth2): correctly handle callback with hash

---

lib/core/middleware.js

As I [commented](https://github.com/nuxt-community/auth-module/pull/385#issuecomment-504780423) in PR #385, I actually introduced a regression when `callback: false` is set in redirect options,
as it tries to call `normalizePath(callback)`, which calls `callback.split()`, which is not possible when it is set to `false` instead of a `string`.
This PR fixes this.

fix: regression from #385 when callback is set to false

---

docs/readme.md

The link of "Setup auth middleware" in /auth-module/docs/readme.md was broken, so it was fixed.

Fixed broken link in Setup auth middleware

---

lib/core/auth.js

Usefull when subscribed to setLoggedIn mutation and want user object at that stage available

fix(core): set loggedIn after user

---

lib/schemes/refresh.js

If we reject the promise from the refresh token api call, we will get the rejection from the original call. 
This rejection should be handled inside the module and disconnect the user as the refresh token failed.

Avoid rejecting promise from refresh token check

---

examples/demo/pages/login.vue

I think it looks better with columns aligned properly.
What it looks like now:
What it will become:

demo: make the columns properly aligned

---

lib/core/utilities.js

Currently, the `isRelativeURL` regex returns false for urls with only querystring or hash part.
- `/?query=foo`
- `/#bar`.
This prevents redirection to those urls in the auth callback.
This PR fixes the issue.

fix(core): support querystring only url for `isRelativeURL`

---

docs/guide/setup.md

The current version of `nanoid` uses `Math.clz32` which is not supported by IE11. This documentation change explains the need to transpile `nanoid` for projects that need to support IE11.

docs: explain need to transpile nanoid for ie11 support

---

lib/module/index.js

This would already help me fixing my issues using nuxt-auth with vue-stator
For laughs, this is what i do now to fix this:
```js
buildModules: [
async function fixNuxtAuth() {
const authModulePath = require.resolve('@nuxtjs/auth/lib/module/index.js')
const haystack = await fs.readFileSync(authModulePath, { encoding: 'utf8' })
const needle = 'if (!this.options.store) {'
const fixed = 'if (options.vuex && !this.options.store) {'
if (!haystack.includes(needle)) {
if (!haystack.includes(fixed)) {
consola.error(`fix-nuxt-auth: needle & fixed both not found in haystack`)
}
return
}
const content = haystack.replace(needle, fixed)
await fs.writeFile(authModulePath, content)
},
```

fix(module): don't log fatal error when vuex is disabled

---

docs/api/storage.md

Just crawled through the source code and recognized that the "removeUniversal" method is not mentioned in the doc. It's kind of useful

Added "removeUniversal" to storage.md

---

lib/core/utilities.js

Comparing URLs in isSameURL should remove the trailing slash.
Comparison of `https://example.com/signIn` with `https://example.com/signIn/` should return true.

fix: remove the trailing slash of paths in `isSameURL`

---

lib/schemes/local.js

this PR was created to fix issues that were found with the original merge from [PR 278](https://github.com/nuxt-community/auth-module/pull/278)
- remove the logging out as we will overwrite the token anyways and it introduced unexpected and unwanted behaviour
- remove check if we need to use token. this functions purpose is to set the token, so we will always do it

fix: fix `setUserToken` issues

---

lib/schemes/local.js
lib/schemes/oauth2.js

The purpose of this PR is refactor the methods `logoutLocally` of `local` scheme and `logout` of `oauth2` scheme. 
By now they are clearing the tokens and calling `$auth.reset()`, but with these changes they will be the `reset` method. That way, whenever `$auth.reset()` is called (e.g. when `resetOnError` is `true`) it will reset properly.
This closes #172

fix: clear tokens when calling `$auth.reset()`

---

docs/schemes/local.md

Added more descriptions on the login component. Added input fields showing how it actually implemented.

docs: improve local example for `loginWith`

---

docs/schemes/local.md
lib/core/auth.js
lib/schemes/local.js
test/module.test.js

Fix issue #144 
This closes #144, closes #411 and closes #249

feat(core): return response from `loginWith`

---

lib/core/auth.js

This PR allow `requestWith` to return response.
This fix is required to return response from [refreshToken method](https://github.com/nuxt-community/auth-module/blob/feat/refresh/lib/schemes/refresh.js#L145) of #361

feat(core): support getting response with `requestWith` utility

---

test/module.test.js

This PR fix the `logout` test. 
It will fix the value of  `loginToken` and `logoutToken` properties and expect `logoutToken` to be `false` instead of `null`

test(logout): fix token properties and expect `logoutToken` to be `false`

---

docs/api/auth.md
docs/api/storage.md
docs/providers/auth0.md
docs/providers/facebook.md
docs/providers/github.md
docs/providers/google.md
docs/providers/laravel-passport.md
docs/schemes/local.md
docs/schemes/oauth2.md

Commit 6af5b0f78c2d067cd020f13bd9a7c6c040942688 introduced a typo in a few links (a `/` is missing)

docs: fix typo in links

---

docs/api/auth.md
docs/schemes/local.md

This PR add `setUser` documentation. `setUser` is required to manually set the user when `autoFetchUser` is disabled.

docs: add `setUser` documentation

---

docs/api/auth.md

I accidentally added `await` to `setUser` example. This PR will remove it.

docs(auth): remove `await` from `setUser` example

---

lib/schemes/oauth2.js
lib/schemes/refresh.js

Refresh token should only be updated if defined in response of refresh endpoint.
> The response will be a new access token, and optionally a new refresh token, just like you received when exchanging the authorization code for an access token.
>If you do not get back a new refresh token, then it means your existing refresh token will continue to work when the new access token expires.
This fixes #592

fix(oauth2, refresh): only update refresh token if defined in response

---

docs/api/options.md

Since the auth middleware only runs either on the server or client side on first request (but not both), cookies are required unless you want janky logouts every time a user refreshes the page followed by janky logins next time they click a link.
See more info here:
https://github.com/nuxt-community/auth-module/issues/478#issuecomment-612659009

docs(options): mention cookies are required for ssr

---

docs/schemes/local.md

Fixing properties in data object. Should be 'username', not 'email'.

demo: fix `data` object property

---

lib/schemes/oauth2.js

Fixes issue where the access token and expiration are stored as the refresh token and expiration.
This closes #562

fix(oauth2): correctly set `refreshToken`

---

docs/.vuepress/config.js
docs/providers/laravel-sanctum.md
docs/schemes/cookie.md
docs/schemes/local.md
examples/demo/nuxt.config.js
examples/demo/pages/login.vue
lib/core/auth.js
lib/core/storage.js
lib/core/utilities.js
lib/providers/laravel.sanctum.js
lib/schemes/cookie.js
lib/schemes/local.js
lib/schemes/oauth2.js
lib/schemes/refresh.js

- feat(auth): support strategy.check
- This new hook allows strategies to validate loggedIn status based on their logic in addition to basic user boolean check
- New cookie scheme
- based on local
- token disabled by default
- csrf endpoint support
- `XSRF-TOKEN` cookie checker for loggedIn 
- Added Laravel [Sanctum](https://laravel.com/docs/7.x/sanctum) provider
- based on cookie scheme with decent defaults
- Added to the demo
- added new `getResponseProperty` util to be able to read from headers or status
- request and requestWith utils directly return response
Credits: #557 #556 to @JoaoPedroAS51 :green_heart:

feat: cookie scheme and laravel sanctum

---

lib/core/auth.js

This error will be thrown if you try to set an undefined strategy. For example when using `this.$auth.loginWith('my-undefined-strategy')`
There are two cases: 
- If your strategy wasn't added to auth config.
- If your strategy scheme wasn't found. 
The current error:
---
With this fix:
---

fix(core): throw error if trying to set an undefined strategy

---

lib/module/index.js

Fixes the following compile error:
```
This relative module was not found:
* ./local in ./.nuxt/auth/schemes/cookie.js
```

fix(cookie scheme): include parent scheme during build

---

src/module/resolve.ts

Throw an error if strategy scheme wasn't found.
Example code:
```js
myStrategy: {
// Missing scheme: 'local'
token: {
property: 'token.accessToken'
}
},
```
The current error:
---
With this fix:
---

fix(module): throw error if scheme is not defined

---

demo/pages/login.vue
src/providers/_utils.ts

This PR fixes the error response of `addAuthorize` and `initializePasswordGrantFlow`.
It returns the data provided by the original response instead of returning NuxtServerError. That way we can access the error message of the response.
Fixes #659

fix(provider utils): return correct error response

---

src/schemes/cookie.ts

Seems that Laravel Sanctum requires `referer` header in SSR request to authorize the request. This fix will set `referer` header on mount. 
This also set token `maxAge` to `false` as we are not using token.
Fixes #653

fix(laravel sanctum): set `referer` header on mount

---

docs/api/refreshController.md
src/inc/refresh-controller.ts
src/inc/request-handler.ts
src/schemes/oauth2.ts
src/schemes/refresh.ts

Unify method `initializeRequestInterceptor` of RefreshController with RequestHandler. This make it clear and easier to use. RefreshController class only handles refresh now.

refactor(request handler, refresh controller): unify request interceptor

---

src/schemes/local.ts
src/schemes/oauth2.ts
src/schemes/refresh.ts
src/utils/index.ts

- Add new private method `_updateTokens` that is used to update token and refresh token values. That way we can remove `login` method from refresh scheme as it becomes identical to local scheme method. 
- Add new private method `_checkStatus` that is used to check status of token and refresh token. It forces reset if refresh token has expired or if `autoLogout` is enabled and token has expired. That way we can remove `mounted` method from refresh scheme as it is identical to local scheme method.
- Remove `fetchUser` from refresh scheme as it is identical to local scheme method.

refactor(schemes): simplify schemes removing duplicates

---

src/inc/refresh-controller.ts
src/inc/request-handler.ts
src/schemes/oauth2.ts
src/schemes/refresh.ts

Fix an issue that was preventing other requests if refresh request failed.
Also add support to catch errors from `$auth.refreshTokens()`

fix: catch refresh request error

---

docs/providers/laravel-sanctum.md

Missing provider in second example causes a scheme-not-found error when trying to start nuxt.
```js
{
axios: {
proxy: true
},
proxy: {
'/laravel': {
target: 'https://laravel-auth.nuxtjs.app',
pathRewrite: { '^/laravel': '/' }
}
},
auth: {
strategies: {
'laravelSanctum': {
//provider: 'laravel/sanctum', <-- This was missing
url: '<laravel url>'
}
}
}
}
```

docs: add missing provider key to laravelSanctum example

---

src/providers/laravel/passport.ts

Axios `baseURL` should be ignored for password grant flow as `login` and `refresh` endpoints are `serverMiddleware`.
Fixes #682

fix(laravel passport): ignore axios `baseURL` for password grant flow

---

src/inc/request-handler.ts

This change is needed for using other api's auth because the onRequest is called on each request made with axios so each auth of others api's requests are override by the module token.

fix(request handler): only intercept requests if global token is enabled

---

docs/providers/auth0.md
docs/schemes/oauth2.md
src/providers/auth0/index.ts
src/providers/auth0/scheme.ts

This PR sets the `token` and `logout` endpoint for the `Auth0` provider. I updated the docs accordingly.

fix(auth0): set token and logout endpoint, and update docs

---

demo/pages/secure.vue
docs/providers/laravel-sanctum.md
src/core/auth.ts
src/core/middleware.ts
src/inc/refresh-token.ts
src/inc/request-handler.ts
src/inc/token.ts
src/index.ts
src/module/defaults.ts
src/providers/laravel/passport.ts
src/schemes/cookie.ts
src/schemes/local.ts
src/schemes/oauth2.ts
src/schemes/refresh.ts
test/e2e.test.js

Initialize Token and Refresh Token instances inside schemes. Both classes now use scheme options instead of `$auth`. Also move token and refresh token prefixes to scheme `DEFAULTS`.
Improve `check` method to also check tokens status, deprecating `_checkStatus`. Return object with token and refresh token expired status.
```js
{
valid: boolean,
tokenExpired: boolean,
refreshTokenExpired: boolean,
isRefreshable: boolean
}
```
**Note:** `valid` is the only required property.
Alias `HTTPRequest` to `AxiosRequestConfig` and `HTTPResponse` to `AxiosResponse`.
RequestHandler class now use scheme options and methods instead of `$auth`.

feat: improve token handling and validation

---

src/schemes/local.ts
src/schemes/refresh.ts

Using this method makes it easier to set the refresh endpoint. Just need to override it in `refresh` scheme. That way we don't need to pass `refreshEndpoint` everywhere the interceptor is initialized.

refactor(local, refresh): add method `_initializeRequestInterceptor`

---

src/providers/laravel/jwt/index.ts
src/providers/laravel/jwt/scheme.ts
src/schemes/refresh.ts

Set refresh token to `true` instead of `false` if refresh token is not required. That way refresh token expiration is set. And add `isRefreshing` and `updateOnRefresh` params to be able to not update refresh token expiration if refresh endpoint doesn't refresh the refresh token.
Also simplify `check` as refresh token will always be `true` when not required.
Add custom scheme for Laravel JWT provider to not update refresh token expiration on refresh.

fix(refresh scheme): fix non-required refresh token flow

---

src/core/auth.ts
src/schemes/local.ts
src/schemes/refresh.ts

Improve `setUserToken` to set refresh token as second parameter and fix `setUserToken` of `local` scheme.

feat: improve `setUserToken` to set refresh token

---

docs/schemes/refresh.md
src/providers/laravel/jwt/index.ts
src/schemes/refresh.ts

If `tokenRequired` is enabled, Authorization header won't be cleared before refreshing. Disabled by default.
Also fix Laravel JWT provider by enabling `tokenRequired` option.

fix(refresh scheme): add `tokenRequired` option for refresh token

---

src/schemes/oauth2.ts

As designed, we cannot add additional options when extending the Oauth2Scheme. To make options extensible, I borrowed code from the LocalScheme implementation which lets us pass the child's default options up to its parent.

fix(oauth2 scheme): make options extendable

---

src/schemes/oauth2.ts

We recently migrated from Laravel Passport's password grant to standard OAuth and have run into this issue. Our userInfo method returns a user object wrapped in a data parameter. Using the password grant, we were able to user the user.property setting to specify where to find the user object being returned from the server. This broke when we switched schemes. The OAuth scheme currently ignores the user.property setting. This fixes the issue and brings the code closer to what is defined in other schemes.

Fix OAuth scheme ignoring user.property setting

---

docs/content/en/providers/laravel-sanctum.md

Although outside the scope of this package. I would recommend adding this to the docs. Otherwise all follow up Axios request will fail.
**Without** the credentials in Axios:
```javascript
this.$axios.get('/api/test').then(response => {
console.log(response);
});
```
```
Request URL: http://127.0.0.1:8000/api/test
Status Code: 401 Unauthorized
```
**With** the credentials in Axios:
```javascript
this.$axios.get('/api/test').then(response => {
console.log(response);
});
```
```
Request URL: http://127.0.0.1:8000/api/test
Status Code: 200 OK
```
Since now the `X-XSRF-TOKEN` is set.
Let me repeat: I get it if this is outside the scope of this package. But I assume that 99.99% of the users who implement this, probably want to do a follow up request with Axios to their api.

Update readme Laravel Sanctum add credentials

---

docs/api/options.md

Fixes typo in JS code for options

docs: fix typo in options

---

docs/content/en/api/options.md

fixed incorrect path to "Extending Auth plugin" page

docs: add missing .md

---

docs/content/en/guide/setup.md

I had to search through github issues to figure out where the types files were located.  I made this quick edit to the docs to help others who are struggling with the same issue.
See #274 and #678
- add information about using this module with Typescript.
- add table of contents

docs(setup.md): add info about using module in a TypeScript project

---

src/schemes/oauth2.ts

I noticed when using the built-in "oauth2" scheme that if you reload the page with an active refresh token and an expired access token that I would still be logged out and thrown into the login screen again. Upon further digging the content-type request header is missing for server-side access_token refresh.

fix(oauth refresh): OAuth2 scheme token refresh not working server-side and silently errors out

---

lib/schemes/oauth2.js

Fix nanoid import as verified by https://github.com/nuxt-community/auth-module/issues/750#issuecomment-652149593 and https://github.com/nuxt-community/auth-module/pull/751#issuecomment-661398859 and https://github.com/nuxt-community/auth-module/issues/772#issuecomment-662886676
Closes https://github.com/nuxt-community/auth-module/issues/750
Closes #772
Closes https://github.com/nuxt-community/auth-module/issues/812
Closes https://github.com/nuxt-community/auth-module/pull/751 (superseded)

fix(oauth): nanoid import

---

demo/api/auth.js

This PR fix the error `algorithms should be set` of `express-jwt` (**v5**)

demo: add express-jwt algorithms

---

docs/content/en/schemes/oauth2.md

The path to authO provider wasn't working.
This patch should fix it.

docs: Fix path in oauth2.md

---

src/core/middleware.ts

Fixes an unhandled exception when the middleware tries to refresh the token but the http-request fails.

fix(core): error handling for token refresh in middleware

---

src/schemes/oauth2.ts

While _handleCallback has unset the baseURL when calling the token endpoint, refreshTokens currently uses the existing Axios baseURL.
This causes issues in cases where addAuthorize was used (i.e. the github strategy) as the new token endpoint becomes a relative URL pointing to the Nuxt server middleware.

fix(oauth2 scheme): unset baseURL in refreshTokens

---

src/utils/index.ts

Fix "TypeError: Cannot use 'in' operator to search for 'token'"
Thanks to @CraftingGamerTom
Closes #699, #738

fix(utils): check if `holder` is `object` in `getProp` util

---

src/schemes/local.ts

When option `token.required` is set to `false`, it should set the token value to `true` instead of disabling token check. This is the correct approach and is already being used in [refresh scheme](https://github.com/nuxt-community/auth-module/blob/dev/src/schemes/refresh.ts#L214)

fix(local scheme): fix behaviour when token is not required

---

src/core/auth.ts
src/inc/request-handler.ts
src/inc/token.ts
src/utils/index.ts

When we improved the module types in #922, the axios `setHeader` was complaining about the token not being an string, so I converted it to string using `+ ''`. But it caused an issue when token is set to `false`, as it was converting `false` to string instead of unset the token and authorization header.
Fixes #949 
I couldn't reproduce #945 issue, but seems to be releated to this. So, it possibly fixes #945
After merging, developers facing the issue should test and see if it solves the issue.

fix: only set authorization header when token is string

---

src/schemes/cookie.ts

Now that the behaviour when token is not required has been fixed, we can safely use `token.required` set to `false` in cookie flow, instead of using `token.property` set to `.status`
I believe we can also deprecate `getResponseProp` util in another PR. (Use `getProp` instead)

fix(cookie scheme): use `token.required` instead of `token.property`

---

docs/content/en/api/options.md

Hi! Loving v5 of this project and my team has been actively using it in a few projects.
I came across this grammatical error a few times and couldn't help but to create a PR for it. Haha.

docs: fix grammatical error in options documentation

---

package.json

Node 12+ uses  exports field in `package.json` to find main file.  
The main exports was missing in the package.json and it leads to `ERR_PACKAGE_PATH_NOT_EXPORTED` error.
close #987

fix: export main file

---

docs/content/en/status.md

Changed `@nuxt/auth-next` to proper package name: `@nuxtjs/auth-next`

fix: Changed package name in the docs

---

docs/content/en/guide/scheme.md
src/schemes/local.ts
src/schemes/oauth2.ts
src/schemes/refresh.ts
src/utils/index.ts

The `getResponseProp` util is not useful anymore, since we merged #952

feat: deprecate `getResponseProp`

---

src/schemes/local.ts

This PR adds error Handling for 2 Error cases in fetchUser instead of silently failing.
- fetchUser Promise is rejected if the field options.user.property does not contain data in the fetchUser response
- fetchUser Promise is rejected if the Requests Promise was rejected

fix: Add error handling for user data fetching

---

docs/content/en/glossary.md

"Read more" link is pointing to the wrong url .

docs: Correct hyperlink to "Schemes and Strategies"

---

src/schemes/oauth2.ts

Keycloak required nonce for response_type=token but there was no way I was able to set nonce.

feat(oauth2): make nonce settable when response_type includes 'token'

---

src/options.ts

The `auth.plugins` option should be able to use both types of arrays. 
ref: https://auth.nuxtjs.org/recipes/extend

chore(type):  `auth.plugins` option can mix use string[] and object[]

---

docs/content/en/api/auth.md

The link to the tokens page was incorrect before and led to a 404 error on the documentation page. This commit fixes it.

Fix link to tokens page

---

src/core/auth.ts

Fix request for relative endpoints in server side, which was affecting all providers.
Due to this issue, refreshing token was not working on page reload.
Definitely fixes #1178

fix(core): fix baseURL for relative endpoints

---

docs/content/en/api/options.md

Very minor edit on the documentation.

docs(api): fix typo in options.md

---

docs/content/en/api/auth.md

Before :
$auth.token and $auth.refreshToken
After: 
$auth.strategy.token.get()
$auth.strategy.refreshToken.get()

docs(api): fix access of token and refresh token instances

---

docs/content/en/guide/setup.md

In the setup section there is a warning about Vuex. In it there are two links, both of which were returning 404s. Changed the paths, which appear to the correct location.

Fixed 404ed links to Vuex

---

docs/content/en/schemes/local.md
docs/content/en/schemes/refresh.md

In a previous version, I believe that propertyName could be placed in the user option within endpoints. This led to some confusion for me when switching to auth-next, so I've added some clarification.

docs: Add clarification to user options placement

---

docs/content/en/recipes/extend.md

If you follow this guide then it instructs you to install `@nextjs/auth-next` but in the extending the plugins recipe it referenced the package that is not from the install section leading to errors in the app.

Referencing the correct package name.

---

demo/pages/login.vue

When you enter an invalid password in the demo, no error is shown. Nothing happens:
That's because the response body itself is not just the error object, rather it has the error object in its `error` property. So this change is to correctly pull the error out of the response body.
After the fix:

fix: Make invalid password error appear properly in demo

---

docs/content/en/schemes/local.md

This is as much an issue as it is a pull request. Currently your token will not appear in vuex with the default prefix (`_token.`). For me, this is unexpected and at the least should be documented, but may also be a bug.
The "offending" line is:
https://github.com/nuxt-community/auth-module/blob/f6990742fb282663fe93d2dfc8091a62275a0ecc/src/core/storage.ts#L138 
With the default prefix, the token is not added to the vuex store. At the very least, this should be documented, but I argue that the default prefix should be changed (maybe to just `token`). What are the consequences of this?
Thanks for the lib! :)

docs: Document logic for storing the token in vuex state

---

src/options.ts

this is regarding an issue: https://github.com/nuxt-community/auth-module/issues/1358 where working feature (disabling redirect), mentioned in documentation was not included in `src/options.ts` `ModuleOptions.redirect` type description

Added missing secondary types on `ModuleOptions.redirect`

---

src/schemes/oauth2.ts

Currently, it is not possible to disable the redirect to 'home' caused by the default oauth2 scheme. 
As described in the [Options#watchLoggedIn](https://github.com/nuxt-community/auth-module/blob/3c73e64a4f03907fa9370427fe74978ec17965df/docs/content/en/api/options.md#watchloggedin) documentation, the `watchLoggedIn` property in the auth module configuration should disable this behaviour.
If the user is expected to modify this behaviour by extending the default oauth2 scheme instead, it would require a complete "reimplementation" (copy) of the `_handleCallback` function.
This PR prevents duplicate code and makes the oauth scheme respect the `watchLoggedIn` property set in the auth-module configuration.

fix(oauth2 scheme): Make oauth2 scheme respect `watchLoggedIn` property
