nuxt-community/auth-module

.gitignore
README.md
package.json
src/index.js
templates/auth.store.js

- Implementation of global configurations with default values (auth options). 
- Removal of the extra parameters of the actions.
- Adding some extra configuration parameters.
- Code optimization.
- Documentation update.

Improvements

---

README.md
lib/module.js
lib/templates/auth.store.js

Add possibility to set the request to POST or GET with user option.

Add possibility to set the request to POST or GET.

---

README.md
lib/module.js
lib/templates/auth.store.js

Add optional errorHandler for fetch and logout.
As example, when fetch get an exception, I wanna show message for user (i.e. your session expired) in custom error handler.

add errorHandler option

---

lib/templates/auth.class.js

Fix calling fetchUser() while fetchUserOnLogin() is disabled.
Fixes #59

Fix calling fetchUser() without need

---

lib/auth/auth.js

This pull request aims to fix some minors issues on the develop branch before implementing any *non-breaking changes features* or going any further in the release candidate process.

fix: stability fixes for future release candidate

---

lib/core/storage.js

Check for req object on getCookie function

---

lib/core/auth.js

Typo syncRefreshToken

---

docs/schemes/oauth2.md

add comma following _scheme value

---

docs/options.md

Bugfixes:
- fixes example by changing `user` to `home`
- fixes broken link to `defaults.js`

Fixes options.md docs

---

lib/core/utilities.js

fix: randomString for SSR

---

lib/providers/_utils.js

Removes the deprecation warning

Set extended for body-parser urlencoded

---

docs/SUMMARY.md

This PR fixes a couple of spelling mistakes in the docs.

Fix spelling mistakes

---

lib/core/auth.js

hello, i found and fixed a bug.
if the this.mounted() throw an exception，this.$storage.watchState not be called

fix: auth init

---

docs/api/storage.md

change setLocalstorage to setLocalStorage with capital Storage

docs: fix $storage.setLocalstorage

---

docs/recipes/extend.md

Update modules value from object to array.
https://nuxtjs.org/api/configuration-modules

docs: fix modules value from object to array

---

docs/options.md

closing brace was not inside code formatting

docs: correct code formatting

---

docs/schemes/local.md

Based on [this](https://stackoverflow.com/questions/52576160/nuxt-auth-user-data-not-set)

docs: mention `propertyName` should be set to `false` 

---

lib/core/auth.js

fix: preserve query params when redirect

---

lib/core/utilities.js

this help when use other service by oauth2

fix(utilities): avoid send xxx=undefined in query

---

package.json

chore(deps): Move body-parser to dependencies

---

docs/recipes/extend.md

Not having this was a serious pain.

docs: update extend.md

---

CHANGELOG.md
docs/package.json
docs/readme.md
docs/yarn.lock
examples/demo/pages/login.vue
lib/schemes/oauth2.js
package.json
yarn.lock

Hey @pi0 !  
I made the video tutorial we talked about.  Hopefully this current version will work, but if there are changes you'd like to see then let me know - I can re-cut the video as needed to make it work better for embedding.
Thanks so much for all the work you do on this module!

docs: add video totourial

---

docs/glossary.md

broken links are here -> https://auth.nuxtjs.org/glossary.html

Fix broken links in docs

---

lib/core/auth.js

Actually it fails silently 😬
I think we can do better still

chore(core): throw error if axios module is not used

---

lib/schemes/oauth2.js

feat(oauth2): customizable `token_key` and `refresh_token_key` options

---

docs/schemes/local.md

I have modified the sample code of Local Scheme to work as I expected.
I propose to change that.

docs: improve local example

---

docs/guide/setup.md

added link on how to activate Vuex Store

docs(setup): added link on how to activate vuex store

---

docs/api/storage.md

These methods are changed this commit  d05fcca.

docs: fix storage methods arguments

---

docs/schemes/oauth2.md
lib/core/auth.js
lib/schemes/oauth2.js

feat(oauth2): logout support

---

docs/providers/laravel-passport.md
lib/providers/laravel.passport.js

Set token and refresh token defaults. It also update the docs to provide information about token lifetimes and user endpoint.

fix(laravel-passport): add refreshToken defaults

---

examples/demo/pages/login.vue

Show the error message "Invalid username or password" from response

demo: fix login error message

---

lib/providers/_utils.js

Add refresh tokens support and fix token endpoint from `addAuthorize`

feat(provider-utils): add refresh token support and fix token endpoint from addAuthorize

---

examples/demo/pages/secure.vue

Show current refresh token and refresh tokens button for all strategies.

demo: show refresh tokens for all strategies

---

lib/schemes/oauth2.js
lib/schemes/refresh.js

fix(oauth2, refresh): remove authorization header from refreshToken call

---

docs/schemes/oauth2.md

docs(oauth2): add grantType documentation

---

docs/.vuepress/config.js
docs/providers/laravel-jwt.md
docs/schemes/refresh.md

docs: update refresh scheme and add laravel jwt provider

---

docs/schemes/oauth2.md
src/schemes/oauth2.ts

Add auto logout function to `oauth2` scheme. Same as `refresh` scheme.

feat(oauth2 scheme): add `autoLogout`

---

src/core/auth.ts
src/inc/request-handler.ts
src/providers/auth0/scheme.ts
src/schemes/cookie.ts
src/schemes/local.ts
src/schemes/oauth2.ts
src/schemes/refresh.ts

Make `reset` method synchronous.

refactor: synchronous reset

---

docs/schemes/local.md

Add missing documentation about `globalToken`.

docs(local scheme): add `globalToken`

---

src/core/auth.ts
src/inc/request-handler.ts
src/schemes/local.ts
src/schemes/oauth2.ts
src/schemes/refresh.ts

Eject scheme interceptor on reset, preventing from having more than one set.

fix: eject interceptor on reset

---

docs/readme.md

Updates to sentence structure, grammar, and spelling.

docs: update readme.md

---

src/core/storage.ts

Search for cookies with the same name and remove the cookie with old value.
Fixes #671

fix(storage): improve `setCookie` to prevent duplicated cookies

---

docs/schemes/local.md
docs/schemes/refresh.md
src/schemes/local.ts
src/utils/provider.ts

Pass all data from original requests to the new requests. Also add `scope` support.

feat: improve password grant flow

---

jest.config.js
package.json
test/e2e.test.ts
test/tsconfig.json
yarn.lock

Add typescript support for jest and fix test errors.

test: use ts-jest and babel

---

docs/content/en/providers/auth0.md
docs/content/en/providers/facebook.md
docs/content/en/providers/github.md
docs/content/en/providers/google.md
docs/content/en/providers/laravel-jwt.md
docs/content/en/providers/laravel-passport.md
docs/content/en/providers/laravel-sanctum.md

docs: fix broken links

---

docs/content/en/index.md

Broken following https://github.com/nuxt-community/auth-module/pull/621

docs: fix broken link to examples

---

src/providers/laravel/sanctum.ts

grammar mistake error laravel Laravel Sanctum

grammar mistake

---

docs/package.json
docs/yarn.lock

docs: update dependencies

---

docs/content/en/guide/setup.md
docs/package.json
docs/yarn.lock

Update info about using module in a TypeScript project (**auth v5**)
Auth v5 should use types from `@nuxtjs/auth-next`

docs(setup.md): update info about using module in a TypeScript project

---

examples/api/auth.js

This PR fix the error `algorithms should be set` of `express-jwt` (**v4**)

demo: add express-jwt algorithms

---

docs/content/en/api/tokens.md

Closes https://github.com/nuxt-community/auth-module/issues/844

chore(docs): Correct way to get and set tokens

---

src/inc/refresh-token.ts
src/inc/token.ts

This fix typescript error after migrating to `jwt-decode` v3

fix(token and refresh token): set type of `jwt-decode` payload

---

docs/providers/facebook.md

Updated graph api version to 6.0, scopes changed only to public profile dat

chore(docs): Update facebook example to graphql 6.0, change scopes only to public data

---

docs/content/en/providers/facebook.md

Brought upstream from https://github.com/nuxt-community/auth-module/pull/564

chore(docs): Use newer graphql version for Facebook, and avoid restricted data

---

docs/content/en/api/storage.md

- Under LocalState, `removeState(key)` was added
- Under Cookies, `getCookies()` & `removeCookie(key, isJson)` were added
- Under LocalStorage, `removeLocalStorage(key)` was added

docs: add undocumented functions for storage

---

docs/content/en/guide/setup.md

chore(docs): Remove redundant auth-next install

---

package.json
yarn.lock

See the related issue: axios/axios#3410, which is a security fix.
Thank you!

Bump axios dependencies

---

docs/content/en/api/auth.md
docs/content/en/providers/google.md
docs/content/en/schemes/oauth2.md

@bmulholland referencing your comment on #991

docs: Add example of strategy-specific arguments in use

---

docs/content/en/providers/github.md

The source code link was wrong.

fixed the source code

---

src/utils/index.ts

fix: Allow dots on relative urls

---

src/options.ts

`auth.localStorage` to accept `false` value. 
ref: https://auth.nuxtjs.org/api/options#localstorage

chore(type): Fixed `auth.localStorage` type error

---

src/utils/index.ts

fix: Allow colon in relative URLs

---

src/core/auth.ts
src/providers/laravel-passport.ts
src/schemes/oauth2.ts

fix(core): fix `baseURL`

---

docs/content/en/index.md

improvement(docs): extend introduction to quickly clarify module scope
